[book]
authors = ["Leon"]
language = "en"
multilingual = false
src = "src"
title = "Dora-rs openloong文档"

[output.html]
fold.enable = true
git-repository-url = "https://github.com/dora-rs-org/openloong"

[preprocessor.langtabs]

[preprocessor.alerts]
